# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
nfpms:
  - homepage: https://github.com/aminehmida/medots
    maintainer: Amine Hmida <aminehmida@gmail.com>
    license: GPL-3.0
    formats:
      - apk
      - deb
      - rpm
brews:
  - name: medots
    homepage: https://github.com/aminehmida/medots
    tap:
      owner: aminehmida
      name: homebrew-medots
aurs:
  - homepage: https://github.com/aminehmida/medots
    description: "Cross-platform dot config files manager using a yaml file."
    maintainers:
      - 'Amine Hmida <amine hmida at gmail dot com>'
    license: GPL-3.0
    git_url: 'ssh://aur@aur.archlinux.org/medots-bin.git'
    commit_author:
      name: Amine Hmida
      email: aminehmida@gmail.com
    private_key: '{{ .Env.AUR_KEY }}'
    skip_upload: false
checksum:
  name_template: 'checksums_sha256.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
